package com.balfouriana.domain

enum class ParseRejectionCode {
    EMPTY_PAYLOAD,
    UNSUPPORTED_FORMAT,
    UNDECODABLE_CONTENT,
    STRUCTURALLY_INVALID_RECORD,
    MISSING_REQUIRED_FIELD,
    INVALID_DATE_FORMAT,
    INVALID_NUMBER_FORMAT,
    MAPPING_FAILED,
    PARSER_FAILURE
}
